### ISSUE TITLE
Doesn't work with multiline label and big text.

### ISSUE THREAD

**Issue by zeeshankhan** [danielgalasko/DGSelfSizingCollectionViewCells#3]
Hi,
When i changed the number of lines to 0 and tried with longer strings, it crashes with this message: _the behavior of the UICollectionViewFlowLayout is not defined because: the item width must be less than the width of the UICollectionView minus the section insets left and right values.Please check the values return by the delegate._

**Comment by danielgalasko** [comment]
That is the expected behaviour and your error is telling you exactly that. The width of the label is not constrained so naturally they will try and be as long as possible. If you want multiline labels you will need to add a width constraint
