### ISSUE TITLE
App crashes at launch :O

### ISSUE THREAD

**Issue by hosamhassan** [danielgalasko/DGSelfSizingCollectionViewCells#4]

**Comment by danielgalasko** [comment]
Looked into this, seems like on iOS 9 everything falls apart when the estimatedItemSize is wildly different from the actual estimate. I tweaked stuff around and that fixed the issue.

However, self sizing is still pretty crap and there are loads of issues still prevailing like the contentSize being incorrect and missing rows entirely.

Wondering if a better demo could be created to more accurately reflect a "simpler" scenario. Could include a disclaimer as well warning people of pitfalls...

Thoughts @hosamhassan ?

**Comment by tonyxiao** [comment]
@danielgalasko Where can I find the tweaks that fixed the issue? Can you illustrate it a little more?

**Comment by danielgalasko** [comment]
@tonyxiao The tweaks were not conclusive enough for me to actually fix the issue. Unfortunately I can't seem to get self sizing working adequately on iOS 9. The basic idea was that adding explicitly width constraints to the cells and improving the estimate the app no longer crashed. However, this didn't exactly improve the self sizing nature of the cells and there was still artefacts and missing spaces etc.

The next thing I want to try is perhaps building the cells programmatically and see from there. Would welcome any PR's managing to solve this

**Comment by hosamhassan** [comment]
I ended up using  the sizeWithAttributes NSString method to get the size and it worked perfectly on iOS 9.0

## 

Hosam H.
Lead Software Engineer and co-founder 
Taphive GmbH
Twitter     @TodoMoviesApp https://twitter.com/todomoviesapp
Facebook TodoMovies Page https://www.facebook.com/TodoMovies

**Comment by hokster7** [comment]
Apple:  "Self sizing cells!! Welcome to the dawn of a new age of powerful and easy collection view layouting!"
Developers: **pulls hair out trying to get self sizing to work**

**Comment by danielgalasko** [comment]
@hosamhassan you welcome to take a look at the updated master. I'm not entirely convinced self sizing cells work as advertised but I have a much better understanding now and the App no longer crashes
